version: "3.7"
services:
  bot-db:
    image: postgres:12.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - default
  bot-proxy:
    image: nginx:1.17.8
    ports:
      - 443:443
    volumes:
      - ${PWD}/deploy/local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/deploy/local/nginx/cert_priv.key:/etc/nginx/cert_priv.key
      - ${PWD}/deploy/local/nginx/cert_public.pem:/etc/nginx/cert_public.pem
    networks:
      - default
  # ruby on rails bot
  # bot-ror:
  #   build:
  #     dockerfile: deploy/local/dockerfile-rails-bot
  #     context: .
  #   command: bundle exec rails s -p 3000 -b '0.0.0.0'
  #   volumes:
  #     - ./rails-bot:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - bot-db

# run me with
# docker-compose -f docker-compose-local.yml build
# docker-compose -f docker-compose-local.yml up
